=== Avishek2808/Summer-Paradise/campement.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="summerp">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="campment" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="residence"/>
              <xs:element type="xs:string" name="address"/>
              <xs:element type="xs:integer" name="appartmentNo"/>
              <xs:element type="xs:integer" name="room"/>
              <xs:element type="xs:integer" name="kitchen"/>
              <xs:element type="xs:integer" name="bathroom"/>
              <xs:element type="xs:integer" name="livingRoom"/>
              <xs:element type="xs:string" name="pool"/>
              <xs:element type="xs:string" name="facilities"/>
              <xs:element type="xs:string" name="beach"/>
              <xs:element type="xs:string" name="image" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute type="xs:integer" name="id"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Avishek2808/Summer-Paradise/campement.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="camp.xsl"?>
<summerp xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="campement.xsd">

	<campment id="1">
		<residence>Wonderwoman</residence>
		<address>Coconut lane, Flic en Flac.</address>
		<appartmentNo>6</appartmentNo>
		<room>3</room>
		<kitchen>1</kitchen>
		<bathroom>2</bathroom>
		<livingRoom>1</livingRoom>
		<pool>Common Swimming Pool</pool>
		<facilities>WiFi, Television</facilities>
		<beach>5 minutes.</beach>
		<image>images/premier.jpg</image>
	</campment>
	
	<campment id="2">
		<residence>Superwoman</residence>
		<address>Coconut lane, Flic en Flac.</address>
		<appartmentNo>9</appartmentNo>
		<room>2</room>
		<kitchen>1</kitchen>
		<bathroom>2</bathroom>
		<livingRoom>1</livingRoom>
		<pool>Common Swimming Pool</pool>
		<facilities>WiFi, Television </facilities>
		<beach>7 minutes.</beach>
		<slides>
			<image>deuxieme.jpg</image>
		</slides>
	</campment>
	
	<campment id="3">
		<residence>Lady Gaga</residence>
		<address>Coconut lane, Flic en Flac, Mauritius.</address>
		<appartmentNo>7</appartmentNo>
		<room>3</room>
		<kitchen>1</kitchen>
		<bathroom>2</bathroom>
		<livingRoom>1</livingRoom>
		<pool>Common Swimming Pool</pool>
		<facilities>WiFi, Television</facilities>
		<beach>5 minutes.</beach>
		<slides>
			<image>images/troisieme.jpg</image>
		</slides>
	</campment> 
</summerp>
