=== Avishek2808/Summer-Paradise/clickbait.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="homepage">
		<xs:complexType>
				<xs:sequence>
					<xs:element name="clickbait">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="thumbnail" type="xs:string" minOccurs="0" maxOccurs="1"/>
								<xs:element name="link" type="xs:string" minOccurs="0" maxOccurs="1"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Avishek2808/Summer-Paradise/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="clickbait.xsl"?>
<homepage xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="clickbait.xsd">
	<clickbait>
	  <thumbnail>images\premier.jpg</thumbnail>
	  <link>trial.php</link>
	</clickbait>

	<clickbait>
		<thumbnail>images\deuxieme.jpg</thumbnail>
		<link>second.html</link>
	</clickbait>
	
	<clickbait>
		<thumbnail>images\troisieme.jpg</thumbnail>
		<link>third.html</link>
	</clickbait>
</homepage>
